name = "Hpstr"
license = "MIT"
licenselink = "https://github.com/dldx/hpstr-hugo-theme/blob/master/LICENSE.md"
description = "A Hugo port of the HPSTR theme by Michael Rose (mmistakes)"
homepage = "https://ctownsen357.github.io/"
tags = ["responsive", "blog"]
features = ["comments", "scss", "menu"]

[author]
  name = "Chris Townsend"
  homepage = ""

# If porting an existing theme
[original]
  name = "ctownsen357@gmail.com"
  homepage = "http://ctownsen357.github.io/"
  repo = "https://github.com/ctownsen357"
